export const eventData = {
  data: [
    {
      id: 1,
      eventName: 'Bar Camp 2023',
      description: 'It is IT developer knowledge sharing',
      status: 'new',
      approvedBy: null,
      img: '/events/img1.jpg',
      fromDate: new Date(),
      toDate: new Date(),
      fromTime: '9:00 AM',
      toTime: '5:00 PM',
      address: 'MICT Park Yangon',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      eventName: 'Zay Pwal Daw',
      description: 'It is the shopping festival',
      status: 'approved',
      approvedBy: 'John',
      img: '/events/img2.jpg',
      fromDate: new Date(),
      toDate: new Date(),
      fromTime: '9:00 AM',
      toTime: '5:00 PM',
      address: 'Junction Square',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      eventName: 'Esport Event',
      description: 'MLBB, Pubg, Dota match',
      status: 'new',
      approvedBy: null,
      img: '/events/img3.jpg',
      fromDate: new Date(),
      toDate: new Date(),
      fromTime: '9:00 AM',
      toTime: '5:00 PM',
      address: 'Yangon',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      eventName: 'Music Festival',
      description: 'Music Festival',
      status: 'new',
      approvedBy: null,
      img: '/events/img4.jpg',
      fromDate: new Date(),
      toDate: new Date(),
      fromTime: '9:00 AM',
      toTime: '5:00 PM',
      address: 'PyiThuYinPyin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      eventName: 'Street Food',
      description: 'Show various food in one place',
      status: 'new',
      approvedBy: null,
      img: '/events/img5.jpg',
      fromDate: new Date(),
      toDate: new Date(),
      fromTime: '9:00 AM',
      toTime: '5:00 PM',
      address: 'MaharBandula Park',
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ],
  metadata: {
    limit: 5,
    pageNumber: 1,
    total: 20,
    totalPages: 10
  }
};
