<?php

use Illuminate\Database\Seeder;
use App\Models\Event;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $events =  [
            [
              'event_name' => 'BarCamp 2023',
              'description' => 'It is IT developer knowledge sharing',
              'from_date' => '2023-02-01',
              'to_date' => '2023-02-02',
              'from_time' => '09:00 AM',
              'to_time' => '05:00 PM',
              'status' => 'approved',
              'approved_by_user_id' => 1,
              'image' => 'storage/events/img1.jpg',
              'address' => 'Ygn',
              'created_at' => new \DateTime(),
              'updated_at' => new \DateTime(),
            ],
            [
                'event_name' => 'Esport Event',
                'description' => 'MLBB, Pubg, Dota match',
                'from_date' => '2023-01-09',
                'to_date' => '2023-01-09',
                'from_time' => '09:00 AM',
                'to_time' => '05:00 PM',
                'status' => 'approved',
                'approved_by_user_id' => 2,
                'image' => 'storage/events/img2.jpg',
                'address' => 'Mdy',
                'created_at' => new \DateTime(),
                'updated_at' => new \DateTime(),
            ],
            [
              'event_name' => 'BarCamp 2022',
              'description' => 'It is IT developer knowledge sharing',
              'from_date' => '2022-02-09',
              'to_date' => '2022-02-09',
              'from_time' => '09:00 AM',
              'to_time' => '05:00 PM',
              'status' => 'approved',
              'approved_by_user_id' => 1,
              'image' => 'storage/events/img1.jpg',
              'address' => 'Ygn',
              'created_at' => new \DateTime(),
              'updated_at' => new \DateTime(),
            ],
            [
                'event_name' => 'New Year Promotion',
                'description' => 'New Year Promotion',
                'from_date' => '2023-01-09',
                'to_date' => '2023-01-09',
                'from_time' => '09:00 AM',
                'to_time' => '05:00 PM',
                'status' => 'approved',
                'approved_by_user_id' => 2,
                'image' => 'storage/events/img3.jpg',
                'address' => 'Mdy',
                'created_at' => new \DateTime(),
                'updated_at' => new \DateTime(),
            ],
            [
              'event_name' => 'Music Festival',
              'description' => 'It is IT developer knowledge sharing',
              'from_date' => '2023-01-09',
              'to_date' => '2023-01-09',
              'from_time' => '09:00 AM',
              'to_time' => '05:00 PM',
              'status' => 'approved',
              'approved_by_user_id' => 1,
              'image' => 'storage/events/img4.jpg',
              'address' => 'Ygn',
              'created_at' => new \DateTime(),
              'updated_at' => new \DateTime(),
            ],
            [
                'event_name' => 'ERKE Buy One Get One',
                'description' => 'ERKE Buy One Get One',
                'from_date' => '2023-02-09',
                'to_date' => '2023-02-09',
                'from_time' => '09:00 AM',
                'to_time' => '05:00 PM',
                'status' => 'approved',
                'approved_by_user_id' => 2,
                'image' => 'storage/events/img5.jpg',
                'address' => 'Mdy',
                'created_at' => new \DateTime(),
                'updated_at' => new \DateTime(),
            ],
            [
              'event_name' => 'Sport Car Show Event',
              'description' => 'Sport Car Show Event',
              'from_date' => '2023-02-09',
              'to_date' => '2023-02-09',
              'from_time' => '09:00 AM',
              'to_time' => '05:00 PM',
              'status' => 'approved',
              'approved_by_user_id' => 1,
              'image' => 'storage/events/img2.jpg',
              'address' => 'Ygn',
              'created_at' => new \DateTime(),
              'updated_at' => new \DateTime(),
            ],
            [
                'event_name' => 'Mobile Phone Promotion',
                'description' => 'Mobile Phone Promotion',
                'from_date' => '2023-02-09',
                'to_date' => '2023-02-09',
                'from_time' => '09:00 AM',
                'to_time' => '05:00 PM',
                'status' => 'approved',
                'approved_by_user_id' => 2,
                'image' => 'storage/events/img3.jpg',
                'address' => 'Mdy',
                'created_at' => new \DateTime(),
                'updated_at' => new \DateTime(),
            ],
            [
              'event_name' => 'ICT Show',
              'description' => 'ICT Show',
              'from_date' => '2023-02-09',
              'to_date' => '2023-02-09',
              'from_time' => '09:00 AM',
              'to_time' => '05:00 PM',
              'status' => 'approved',
              'approved_by_user_id' => 1,
              'image' => 'storage/events/img4.jpg',
              'address' => 'Ygn',
              'created_at' => new \DateTime(),
              'updated_at' => new \DateTime(),
            ],
            [
                'event_name' => 'GShock 50% Discount',
                'description' => 'GShock 50% Discount',
                'from_date' => '2023-02-09',
                'to_date' => '2023-02-09',
                'from_time' => '09:00 AM',
                'to_time' => '05:00 PM',
                'status' => 'approved',
                'approved_by_user_id' => 2,
                'image' => 'storage/events/img5.jpg',
                'address' => 'Mdy',
                'created_at' => new \DateTime(),
                'updated_at' => new \DateTime(),
            ]
          ];
          Event::insert($events);
    }
}
